import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import { NavbarMenu } from "./components/navbarmenu";
import ConnectPage from "./connect/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="relative">
      <head>

      </head>

      <body
      
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <NavbarMenu />

        {children}

        <Footer />
        
      </body>
    </html>
  );
}
