"use client";

import { ReactNode } from "react";

// Helper component for sections
function ProjectSection({
  title,
  children,
}: {
  title: string;
  children: ReactNode;
}) {
  return (
    <section className="mb-20">
      <h3 className="text-center text-slate-400 sm:break-normal max-w-full text-lg sm:text-3xl font-semibold leading-10 tracking-tight">
        {title}
      </h3>
      <div className="flex flex-wrap justify-center gap-x-16 gap-y-20">
        {children}
      </div>
    </section>
  );
}

export default function Trading() {
  return (
    <div>
      <div className="max-w-7xl mx-auto py-20 px-4 md:px-8 lg:px-10">
        <h2 className="text-lg md:text-4xl mb-12 text-slate-400 font-semibold">
          Trading Systems
        </h2>

        <div className="text-slate-500 lg:text-xl md:text-base max-w-2xl lg:max-w-4xl leading-relaxed mb-12">
          <p className="mb-6">
            This page provides additional context on my trading systems background beyond what fits naturally on my résumé.
          </p>
          <p>
            My formal training is in Robotics Engineering, with strong foundations in systems design, applied mathematics,
            control theory, and software engineering. In parallel, I have spent nearly nine years independently studying
            market microstructure, derivatives, and systematic trading design, while designing, implementing, and
            evaluating algorithmic trading strategies. My focus has been on building research tools that support clear,
            disciplined reasoning about model behavior under live market conditions.
          </p>
        </div>

        <div className="border rounded-3xl text-slate-400/50 mb-12 pt-4 pb-14 bg-black/70 min-w-[410px]">
          <ProjectSection title="Research Visualization Example">
            <div className="w-full max-w-7xl mx-auto px-4">
              <img
                src="/CL.png"
                alt="Crude oil trading strategy research visualization"
                className="w-full h-full object-contain rounded-lg"
              />

              <p className="text-base text-center sm:text-xl mb-2 text-slate-400">
                Research visualization showing live market data, model-derived reference structure,
                and automated trade signals over approximately one year.
              </p>

              <p className="text-sm text-slate-500 mt-3 pt-3 border-t border-slate-700/50">

                The underlying platform provides market data and visualization. All strategy logic,
                signal generation, and trade state handling were designed and implemented by me.
                These examples are provided solely to illustrate system design and research workflow,
                not to disclose proprietary methods or claim statistical edge.
              </p>
            </div>
          </ProjectSection>
        </div>

        <div className="border rounded-3xl text-slate-400/50 mb-12 pt-4 pb-10 bg-black/70 min-w-[410px]">
          <ProjectSection title="Execution and Reporting Output">
            <div className="w-full max-w-7xl mx-auto px-4">
              <img
                src="/CL_Report.png"
                alt="Crude oil trading strategy execution report"
                className="w-full h-full object-contain rounded-lg"
              />

              <p className="text-base text-center sm:text-xl mb-2 text-slate-400">
                Strategy results summary corresponding to the research visualization above,
                reflecting automated trade execution over the same evaluation period.
              </p>

              <p className="text-sm text-slate-500 mt-3 pt-3 border-t border-slate-700/50">
                This report is generated by the underlying trading platform using executed orders
                produced by my strategy logic. It is included to demonstrate end-to-end system
                integration—from signal generation through execution and reporting—rather than
                to emphasize profitability.
              </p>
            </div>
          </ProjectSection>
        </div>
      </div>
    </div>
  );
}
